name: Test Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Workflow ejecutado correctamente"
          date -u
